langauge: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t abid72rizvi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abid72rizvi/react-test npm test -- --coverage

after_success:
  - docker build -t abid72rizvi/multi-client ./client
  - docker build -t abid72rizvi/multi-nginx ./nginx
  - docker build -t abid72rizvi/multi-server ./server
  - docker build -t abid72rizvi/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push abid72rizvi/multi-client
  - docker push abid72rizvi/multi-nginx
  - docker push abid72rizvi/multi-server
  - docker push abid72rizvi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-235549775944'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
